### ISSUE TITLE
Tracking. Out params

### ISSUE THREAD

**Issue by Sebekerga** [Sebekerga/native_api_1c#6]
Ишью для отслеживания разработки _out параметров_

**Comment by Sebekerga** [comment]
Доступна начальная, минимально рабочая версия: 
```toml
[dependencies]
native_api_1c = { git = "https://github.com/Sebekerga/native_api_1c", tag = "impl_out_params" }
```
Пример определения функции с out параметрами:
```rust
#[add_in_func(name = "TransformString", name_ru = "ПреобразоватьСтроку")]
#[arg(Str, as_in)]
#[arg(Str, as_out)]
#[returns(Bool)]
transform_str: fn(&Self, String, &mut String) -> bool,
```
